config:
  ethereum:
    url:
    address:
    mnemonic:

postgres:
  password:

ingress:
  enabled: true
  hosts:
  - some.domain
  tls:
  - hosts:
    - some.domain
    secretName: indexer-service-https
