config:
  # Configuration of connected blockchain metrics and their providers
  chains:
    # mainnet:
    #   providers:
    #   - label: mainnet
    #     url:
    #     features: [ archive ]
    # rinkeby:
    #   providers:
    #   - label: rinkeby
    #     url:
    #     features: [ archive ]
