config:
  ipfs: https://ipfs.network.thegraph.com

postgres:
  db: node
  host: postgres-postgres
  user: node

resources:
  requests:
    cpu: 1
    memory: 0.5Gi
  limits: #TODO: Tune requests/limits during acceptance tests
    cpu: 1.5
    memory: 1Gi

role: "index-node"

monitoring:
  enabled: true
