helmDefaults:
  wait: true

repositories:
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: jetstack
  url: https://charts.jetstack.io
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: postgres-operator
  url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator

environments:
  default:
    values:
    - ./values/infra.yaml

releases:
- name: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  version: ~3.35.0
  installed: {{ .Values.ingressNginx.enabled }}

- name: postgres-operator
  chart: postgres-operator/postgres-operator
  version: ~1.7.0
  # Fixes CRD installation
  disableValidationOnInstall: true
  values:
  - configKubernetes:
      enable_pod_antiaffinity: true
  installed: {{ .Values.postgresOperator.enabled }}

- name: cert-manager
  chart: jetstack/cert-manager
  version: ~1.4.1
  values:
  - installCRDs: true
  installed: {{ .Values.certManager.enabled }}

- name: letsencrypt-prod-clusterissuer
  chart: ../charts/letsencrypt-prod-clusterissuer
  # Fixes CRD installation
  disableValidationOnInstall: true
  values:
  - email: "{{ .Values.email }}"
  needs:
  - cert-manager
  installed: {{ .Values.letsencryptProdIssuer.enabled }}

- name: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  version: ~4.3.1
  installed: {{ .Values.kubernetesDashboard.enabled }}

- name: kubedashboard-admin-sa
  chart: ../charts/kubedashboard-admin-sa
  installed: {{ .Values.kubernetesDashboardSA.enabled }}

- name: prometheus-stack
  chart: prometheus-community/kube-prometheus-stack
  version: ~17.0.3
  # Fixes CRD installation
  disableValidationOnInstall: true
  values:
  - prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
             resources:
               requests:
                 storage: 10Gi
    grafana:
      sidecar:
        dashboards:
          annotations:
            grafana_folder: "Kubernetes"
          folderAnnotation: "grafana_folder"
          provider:
            foldersFromFilesStructure: true
      persistence:
        enabled: true
  installed: {{ .Values.prometheusStack.enabled }}

- name: graph-grafana-dashboards
  chart: ../charts/graph-grafana-dashboards
  values:
  - postgresDatasource: {{ toYaml .Values.postgresDatasource | nindent 6 }}
  installed: {{ .Values.graphGrafanaDashboards.enabled }}
