helmDefaults:
  wait: true

repositories:
- name: jetstack
  url: https://charts.jetstack.io
- name: kubernetes-dashboard
  url: https://kubernetes.github.io/dashboard/

environments:
  default:
    values:
    - ./values/infra.secret.yaml

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  version: ~1.4.1
  values:
  - installCRDs: true

- name: letsencrypt-prod-clusterissuer
  chart: ../charts/letsencrypt-prod-clusterissuer
  values:
  - email: "{{ .Values.email }}"
  needs:
  - cert-manager

- name: kubernetes-dashboard
  chart: kubernetes-dashboard/kubernetes-dashboard
  version: ~4.3.1
  values:
  - protocolHttp: false
