helmDefaults:
  wait: true

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: postgres
  chart: bitnami/postgresql
  version: ~10.4.9
  values:
  - values/postgres.yaml
  - values/postgres.secret.yaml

- name: graphprotocol-node-index
  chart: ./charts/graphprotocol-node
  values:
  - values/graphprotocol-node-index.yaml
  - values/graphprotocol-node.secret.yaml
  needs:
  - postgres

- name: graphprotocol-node-query
  chart: ./charts/graphprotocol-node
  values:
  - values/graphprotocol-node-query.yaml
  - values/graphprotocol-node.secret.yaml
  needs:
  - postgres

- name: graphprotocol-indexer-agent
  chart: ./charts/graphprotocol-indexer
  values:
  - values/graphprotocol-indexer-agent.yaml
  - values/graphprotocol-indexer-agent.secret.yaml
  needs:
  - postgres
