apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphprotocol-indexer-agent.fullname" . }}
  labels:
    {{- include "graphprotocol-indexer-agent.labels" . | nindent 4 }}
spec:
  # There shouldn't be more than 1 indexer agent instance in installation
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "graphprotocol-indexer-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret.yaml: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{-   toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "graphprotocol-indexer-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.config.coordinates }}
            - name: INDEXER_AGENT_INDEXER_GEO_COORDINATES
              value: {{ .Values.config.coordinates | quote }}
            {{- end }}
            - name: INDEXER_AGENT_INDEX_NODE_IDS
              value: {{ required "config.blockIngestorNodeIds wasn't specified" .Values.blockIngestorNodeIds | quote }}
            - name: INDEXER_AGENT_PUBLIC_INDEXER_URL
              value: {{ required "config.publicUrl wasn't specified" .Values.config.publicUrl | quote }}
            - name: INDEXER_AGENT_COLLECT_RECEIPTS_ENDPOINT
              value: {{ required "config.collectReceiptsEndpoint wasn't specified" .Values.config.collectReceiptsEndpoint | quote }}
            - name: INDEXER_AGENT_DAI_CONTRACT
              value: {{ required "config.daiContract wasn't specified" .Values.config.daiContract | quote }}
            - name: INDEXER_AGENT_NETWORK_SUBGRAPH_ENDPOINT
              value: {{ required "config.networkSubgraphEndpoint wasn't specified" .Values.config.networkSubgraphEndpoint | quote }}
            - name: INDEXER_AGENT_ETHEREUM_NETWORK
              value: {{ required "config.ethereum.network wasn't specified" .Values.config.ethereum.network | quote }}
            - name: INDEXER_AGENT_NETWORK_SUBGRAPH_DEPLOYMENT
              value: {{ required "config.subgraphDeployment wasn't specified" .Values.config.subgraphDeployment | quote }}
            - name: INDEXER_AGENT_POSTGRES_DATABASE
              value: {{ required "postgres.db wasn't specified" .Values.postgres.db | quote }}
            - name: INDEXER_AGENT_POSTGRES_HOST
              value: {{ required "postgres.host wasn't specified" .Values.postgres.host | quote }}
            - name: INDEXER_AGENT_GRAPH_NODE_QUERY_ENDPOINT
              value: {{ required "config.graphNodeEndpoints.query wasn't specified" .Values.config.graphNodeEndpoints.query | quote }}
            - name: INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT
              value: {{ required "config.graphNodeEndpoints.admin wasn't specified" .Values.config.graphNodeEndpoints.admin | quote }}
            - name: INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT
              value: {{ required "config.graphNodeEndpoints.status wasn't specified" .Values.config.graphNodeEndpoints.status | quote }}
            {{- if hasKey .Values.postgres.password "fromSecret" }}
            - name: INDEXER_AGENT_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.password.fromSecret.name }}
                  key: {{ .Values.postgres.password.fromSecret.key }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "graphprotocol-indexer-agent.fullname" . }}
          ports:
            - name: metrics
              containerPort: 7300
              protocol: TCP
            - name: management
              containerPort: 8000
              protocol: TCP
            - name: syncing
              containerPort: 8002
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
