{
 "title": "Namespace container resource utilisation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod containers CPU limits utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\",namespace=\"$namespace\"}[5m]) / on (namespace, pod, container) group_left kube_pod_container_resource_limits{resource=\"cpu\", container!=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}/{{pod}}  {{ container }}"
    }
   ]
  },
  {
   "title": "Pod containers CPU request utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container!=\"POD\",namespace=\"$namespace\"}[5m]) / on (namespace, pod, container) group_left kube_pod_container_resource_requests{resource=\"cpu\", container!=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}/{{pod}}  {{ container }}"
    }
   ]
  },
  {
   "title": "Pod containers RAM limits utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container!=\"POD\",namespace=\"$namespace\"}[5m]) / on (namespace, pod, container) group_left kube_pod_container_resource_limits{resource=\"memory\", container!=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}/{{pod}}  {{ container }}"
    }
   ]
  },
  {
   "title": "Pod containers RAM requests utilisation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container!=\"POD\",namespace=\"$namespace\"}[5m]) / on (namespace, pod, container) group_left kube_pod_container_resource_requests{resource=\"memory\", container!=\"POD\",namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}/{{pod}}  {{ container }}"
    }
   ]
  },
  {
   "title": "Volume free space percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{namespace=\"$namespace\"} / on (namespace, persistentvolumeclaim) kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}/{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Volume free inodes percentage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - kubelet_volume_stats_inodes_used{namespace=\"$namespace\"} / on (namespace, persistentvolumeclaim) kubelet_volume_stats_inodes{namespace=\"$namespace\"}",
     "legendFormat": "{{ namespace }}/{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}