{
 "title": "Subgraph indexing performance",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Subgraph blocks behind",
   "type": "timeseries",
   "description": "Shows how many blocks in network is not yet indexed by subgraph deployment.\n\nIt's normal to have a lot of not-indexed blocks if you just added new subgraph.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ethereum_chain_head_number - on(network,pod) group_right deployment_head",
     "legendFormat": "{{ network }}: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Subgraph blocks index rate",
   "type": "timeseries",
   "description": "Shows blocks indexing rate for subgraphs.\nIf subgraph indexed all historical data it's normally to have almost 0 index rate",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "deriv(ethereum_chain_head_number[5m]) - on(network,pod) group_right deriv(deployment_head[5m]) * -60",
     "legendFormat": "{{ network }}: {{ deployment }}"
    }
   ]
  },
  {
   "title": "Subgraph ETH RPC request duration",
   "type": "timeseries",
   "description": "Duration of eth rpc requests grouped by subgraph and eth rpc method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(deployment_eth_rpc_request_duration[5m])",
     "legendFormat": "{{ deployment }} - {{ method }}"
    }
   ]
  },
  {
   "title": "ETH RPC errors per minute (all subgraphs)",
   "type": "timeseries",
   "description": "Shows amount of ETH rpc errors per minute grouped by rpc method",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "increase(eth_rpc_errors{container=\"graphprotocol-node\"}[1m])",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}