apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
data:
  BLOCK_INGESTOR: {{ .Values.blockIngestorNodeId | quote }}
  GRAPH_KILL_IF_UNRESPONSIVE: "true" #TODO: Do we need this value to be configurable?
  postgres_db: {{ .Values.postgres.db }} #TODO: Add required check
  ipfs: {{ .Values.config.ipfs }} #TODO: Add required check
  ethereum: {{ .Values.config.ethereum }} #TODO: Add required check
