apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
data:
  {{- $pgHost := required "postgres.host wasn't specified" .Values.postgres.host }}
  {{- $pgDB := required "postgres.db wasn't specified" .Values.postgres.db }}
  {{- $pgUser := required "postgres.user wasn't specified" .Values.postgres.user }}
  {{- $pgPass := required "postgres.password wasn't specified" .Values.postgres.password }}
  config.toml: |
    [store]
    [store.primary]
      connection = "postgresql://{{ $pgUser }}:{{ $pgPass }}@{{ $pgHost }}/{{ $pgDB }}"
      weight = 0
      pool_size = 10

    [chains]
      ingestor = "{{ .Values.blockIngestorNodeId }}"
      {{- range $name, $conf := .Values.config.chains }}
      [chains.{{ $name }}]
        shard = "primary"
        {{- range $conf.providers }}
        [[chains.{{ $name }}.provider]]
          label = {{ .label | quote }}
          url = {{ .url | quote }}
          features = {{ toJson .features }}
          transport = {{ default "rpc" .transport | quote }}
          {{- with .headers }}
          [headers]
            {{- range $k, $v := . }}
            {{ $k }} = {{ $v | quote }}
            {{- end }}
          {{- end}}
        {{- end }}
      {{- end }}

    [deployment]
    [[deployment.rule]]
      shard = "primary"
      indexers = [ "{{ .Values.blockIngestorNodeId }}" ]
