apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-index
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.config | nindent 2 }}
