apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
spec:
  {{/* There shouldn't be more than 1 index (ingest) graph-protocol node in installation */}}
  {{- if eq .Values.role "index-node" -}}
  replicas: 1
  strategy:
    type: Recreate
  {{- else -}}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
      {{- include "graphprotocol-node.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/configmap.yaml: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{-   toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "graphprotocol-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: node_id
              {{/* Index (ingest) node_id should equal BLOCK_INGESTOR env value to work in this mode */}}
              {{- if eq .Values.role "index-node" -}}
              value: {{ .Values.blockIngestorNodeId | quote}}
              {{- else -}}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
              {{- end }}
            - name: node_role
              value: {{ .Values.role | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "graphprotocol-node.fullname" . }}
            - secretRef:
                name: {{ include "graphprotocol-node.fullname" . }}
          ports:
            - name: metrics 
              containerPort: 8040
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
