apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-index
  labels:
    role: index
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
spec:
  # Index stateful set had always 1 replica cause it could be only one block ingestor node (https://github.com/graphprotocol/graph-node/blob/master/docker/start#L86-L88)
  replicas: 1
  selector:
    matchLabels:
      role: index
      {{- include "graphprotocol-node.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "graphprotocol-node.fullname" . }}-index
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        checksum/configmap.yaml: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        role: index
        {{- include "graphprotocol-node.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: node_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: {{ include "graphprotocol-node.fullname" . }}
            - secretRef:
                name: {{ include "graphprotocol-node.fullname" . }}
          ports:
            - name: metrics 
              containerPort: 8040
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
