apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-index
  labels:
    role: index
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    role: index
    {{- include "graphprotocol-node.selectorLabels" . | nindent 4 }}
