apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphprotocol-node.fullname" . }}-config
  labels:
    {{- include "graphprotocol-node.labels" . | nindent 4 }}
data:
  config.toml: {{ include "graphprotocol-node.config" . | b64enc }}
