helmDefaults:
  wait: true

repositories:
- name: jetstack
  url: https://charts.jetstack.io

releases:
- name: cert-manager
  chart: jetstack/cert-manager
  version: ~1.4.1
  values:
  - installCRDs: true

- name: letsencrypt-prod-clusterissuer
  chart: ./manifests/letsencrypt-prod-clusterissuer
  needs:
  - cert-manager
