apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphprotocol-indexer.fullname" . }}
  labels:
    {{- include "graphprotocol-indexer.labels" . | nindent 4 }}
spec:
  {{/* There shouldn't be more than 1 indexer agent instance in installation */}}
  {{- if eq .Values.role "indexer-agent" -}}
  replicas: 1
  strategy:
    type: Recreate
  {{- else -}}
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
  {{- end }}
  selector:
    matchLabels:
      {{- include "graphprotocol-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret.yaml: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{-   toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "graphprotocol-indexer.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: postgres_db
              value: {{ required "postgres.db wasn't specified" .Values.postgres.db | quote }}
            - name: postgres_host
              value: {{ required "postgres.host wasn't specified" .Values.postgres.host | quote }}
          envFrom:
            - secretRef:
                name: {{ include "graphprotocol-indexer.fullname" . }}
          ports:
            - name: http
              containerPort: 7600
              protocol: TCP
            - name: metrics
              containerPort: 7300
              protocol: TCP
            - name: management
              containerPort: 8000
              protocol: TCP
            - name: syncing
              containerPort: 8001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: metrics
          readinessProbe:
            httpGet:
              path: /
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
