apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphprotocol-indexer.fullname" . }}
  labels:
    {{- include "graphprotocol-indexer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- if eq .Values.role "indexer-agent" }}
    - port: {{ .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
    - port: {{ .Values.service.syncingPort }}
      targetPort: syncing
      protocol: TCP
      name: syncing
    {{- end }}
    {{- if eq .Values.role "indexer-service" }}
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- end }}
  selector:
    {{- include "graphprotocol-indexer.selectorLabels" . | nindent 4 }}
