apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphprotocol-indexer-service.fullname" . }}
  labels:
    {{- include "graphprotocol-indexer-service.labels" . | nindent 4 }}
type: Opaque
data:
  INDEXER_SERVICE_ETHEREUM: {{ required "config.ethereum.url wasn't specified" .Values.config.ethereum.url | b64enc }}
  INDEXER_SERVICE_INDEXER_ADDRESS: {{ required "config.ethereum.address wasn't specified" .Values.config.ethereum.address | b64enc }}
  INDEXER_SERVICE_MNEMONIC: {{ required "config.ethereum.mnemmonic wasn't specified" .Values.config.ethereum.mnemonic | b64enc }}
  INDEXER_SERVICE_POSTGRES_USERNAME: {{ required "postgres.user wasn't specified" .Values.postgres.user | b64enc }}
  {{- if not (hasKey .Values.postgres.password "fromSecret") }}
  INDEXER_SERVICE_POSTGRES_PASSWORD: {{ .Values.postgres.password.value | b64enc | quote }}
  {{- end }}
