# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""

numberOfInstances: 1
volume:
  size: 10Gi
users:
  node: []
  indexer: []
# TODO: Try to delete this section
databases:
  node: "node"
  indexer: "indexer"
postgresql:
  version: "13"

# Workaround NO_SSL mode in graph-node code
# https://github.com/graphprotocol/graph-node/blob/v0.23.1/store/postgres/src/notification_listener.rs#L130
patroni:
  pg_hba:
  - local all all trust
  - host all all 0.0.0.0/0 md5
