name: Lint and Validate Charts
on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install chart testing tools
        uses: helm/chart-testing-action@v2.1.0

      - name: Run chart-testing (lint)
        run: ct lint --all

  kubeval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate
        uses: desaintmartin/helm-kubeval-action@master
        with:
          path: charts
